using AdDatabase.BLL.Entities; using AdDatabase.BLL.Interfaces; using AdDatabase.BLL.Models; using Microsoft.AspNetCore.Identity; using Microsoft.Extensions.Options; using Microsoft.IdentityModel.Tokens; using System.IdentityModel.Tokens.Jwt; using System.Security.Claims; using System.Text;
namespace AdDatabase.BLL.Services;
public class AuthService(IUnitOfWork uow,IPasswordHasher<User> hasher,IOptions<JwtOptions> options):IAuthService {
 public async Task<AuthResult> RegisterAsync(RegisterRequest r,CancellationToken ct){ if(await uow.Users.ExistsAsync(x=>x.Email==r.Email||x.UserName==r.UserName,ct)) throw new InvalidOperationException("Email or username already exists"); var u=new User{Email=r.Email.Trim().ToLowerInvariant(),UserName=r.UserName.Trim(),RoleId=2,Profile=new Profile{FullName=r.FullName}}; u.PasswordHash=hasher.HashPassword(u,r.Password); await uow.Users.AddAsync(u,ct); await uow.SaveChangesAsync(ct); return Token(u,"User"); }
 public async Task<AuthResult> LoginAsync(LoginRequest r,CancellationToken ct){var users=await uow.Users.ListAsync(x=>x.Email==r.Email.Trim().ToLower(),ct); var u=users.SingleOrDefault()??throw new UnauthorizedAccessException("Invalid credentials"); if(hasher.VerifyHashedPassword(u,u.PasswordHash,r.Password)==PasswordVerificationResult.Failed)throw new UnauthorizedAccessException("Invalid credentials"); if(u.Status!="Active")throw new UnauthorizedAccessException("Account disabled"); return Token(u,u.Role?.Name??"User");}
 public Task<User?> GetProfileAsync(int id,CancellationToken ct)=>uow.Users.GetByIdAsync(id,ct);
 private AuthResult Token(User u,string role){var o=options.Value; var exp=DateTime.UtcNow.AddMinutes(o.ExpiryMinutes); var claims=new[]{new Claim(JwtRegisteredClaimNames.Sub,u.Id.ToString()),new Claim(ClaimTypes.NameIdentifier,u.Id.ToString()),new Claim(ClaimTypes.Name,u.UserName),new Claim(ClaimTypes.Role,role)}; var jwt=new JwtSecurityToken(o.Issuer,o.Audience,claims,expires:exp,signingCredentials:new SigningCredentials(new SymmetricSecurityKey(Encoding.UTF8.GetBytes(o.Secret)),SecurityAlgorithms.HmacSha256)); return new(new JwtSecurityTokenHandler().WriteToken(jwt),exp,u.Id,u.UserName,role); }
}
public class AdService(IUnitOfWork uow):IAdService {
 public Task<PagedResult<Ad>> SearchAsync(AdFilter f,CancellationToken ct)=>uow.Ads.SearchAsync(f,ct);
 public async Task<Ad> GetAsync(int id,CancellationToken ct)=>await uow.Ads.GetDetailsAsync(id,ct)??throw new KeyNotFoundException("Ad not found");
 public async Task<Ad> CreateAsync(int uid,CreateAdRequest r,CancellationToken ct){await Validate(uid,r.CategoryId,r.RegionId,ct);var a=new Ad{UserId=uid,Title=r.Title.Trim(),Description=r.Description.Trim(),Price=r.Price,CategoryId=r.CategoryId,RegionId=r.RegionId,ExpiresAt=r.ExpiresAt,Images=(r.ImageUrls??[]).Select((x,i)=>new AdImage{Url=x,SortOrder=i,IsPrimary=i==0}).ToList(),Attributes=(r.Attributes??[]).Select(x=>new AdAttribute{Key=x.Key,Value=x.Value}).ToList()};await uow.Ads.AddAsync(a,ct);await uow.SaveChangesAsync(ct);return a;}
 public async Task<Ad> UpdateAsync(int uid,int id,UpdateAdRequest r,CancellationToken ct){var a=await GetAsync(id,ct);Own(a,uid);await Validate(uid,r.CategoryId,r.RegionId,ct);a.Title=r.Title.Trim();a.Description=r.Description.Trim();a.Price=r.Price;a.CategoryId=r.CategoryId;a.RegionId=r.RegionId;a.ExpiresAt=r.ExpiresAt;if(r.ImageUrls is not null)a.Images=r.ImageUrls.Select((x,i)=>new AdImage{Url=x,SortOrder=i,IsPrimary=i==0}).ToList();if(r.Attributes is not null)a.Attributes=r.Attributes.Select(x=>new AdAttribute{Key=x.Key,Value=x.Value}).ToList();uow.Ads.Update(a);await uow.SaveChangesAsync(ct);return a;}
 public async Task DeleteAsync(int uid,int id,CancellationToken ct){var a=await GetAsync(id,ct);Own(a,uid);uow.Ads.Remove(a);await uow.SaveChangesAsync(ct);}
 async Task Validate(int uid,int cat,int reg,CancellationToken ct){if(!await uow.Users.ExistsAsync(x=>x.Id==uid,ct))throw new KeyNotFoundException("User not found");if(!await uow.Categories.ExistsAsync(x=>x.Id==cat,ct))throw new KeyNotFoundException("Category not found");if(!await uow.Regions.ExistsAsync(x=>x.Id==reg,ct))throw new KeyNotFoundException("Region not found");} static void Own(Ad a,int uid){if(a.UserId!=uid)throw new UnauthorizedAccessException("Not the ad owner");}
}
public class ConversationService(IUnitOfWork uow):IConversationService {
 public Task<List<Conversation>> MineAsync(int uid,CancellationToken ct)=>uow.Conversations.GetForUserAsync(uid,ct);
 public async Task<Conversation> MessagesAsync(int uid,int id,CancellationToken ct){var c=await uow.Conversations.GetWithMessagesAsync(id,ct)??throw new KeyNotFoundException("Conversation not found");Access(c,uid);return c;}
 public async Task<Message> SendAsync(int uid,int id,SendMessageRequest r,CancellationToken ct){var c=await uow.Conversations.GetByIdAsync(id,ct)??throw new KeyNotFoundException("Conversation not found");Access(c,uid);var m=new Message{ConversationId=id,SenderUserId=uid,Body=r.Body,Attachments=(r.AttachmentUrls??[]).Select(x=>new MessageAttachment{Url=x,ContentType="application/octet-stream"}).ToList()};await uow.Messages.AddAsync(m,ct);c.LastMessageAt=m.CreatedAt;uow.Conversations.Update(c);await uow.SaveChangesAsync(ct);return m;} static void Access(Conversation c,int u){if(c.BuyerUserId!=u&&c.SellerUserId!=u)throw new UnauthorizedAccessException("Conversation access denied");}
}
